version: '3.8'

services:
  orchestrator:
    build: 
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: autolaunch_engine
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./orchestrator:/usr/src/app/orchestrator
    restart: always